title: Western Canada Baptist Fellowship
description: Spreading the Gospel across Western Canada

url: http://wcbf.net/
baseurl: ""

paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
paginate: 5

sass:
  style: compressed

navigation:
 - title: Home
   url: /index.html
 - title: Conference
   url: /conference/
 - title: Membership
   url: /membership/
 - title: History and Beliefs
   url: /beliefs/
 - title: Constitution
   url: /constitution/
 - title: Email Newsletter
   url: /newsletter/

# social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com

# google_analytics: "UA-58263416-1"
