title: Western Canada Baptist Fellowship
description: Spreading the Gospel across Western Canada

url: http://duncanjohnson.ca/
baseurl: "/wcbf"

paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Membership
   url: /membership.html
 - title: History and Beliefs
   url: /beliefs.html
 - title: Constitution
   url: /constitution.html
 - title: Email Newsletter
   url: /newsletter.html

# social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com

# google_analytics: "UA-58263416-1"
