title: WCBF
description: Spreading the Gospel across Western Canada

url: http://duncanjohnson.ca/
baseurl: "/wcbf"

paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: History and Beliefs
   url: /beliefs/
    # - title: Constitution
      # url: /beliefs/constitution.html
 - title: Purpose
   url: /purpose

# social:
#    github: brianmaierjr
#    twitter: brianmaierjr
#    facebook: brianmaierjr
#    email: brimaidesigns@gmail.com

# google_analytics: "UA-58263416-1"
